dataset_name: 'darpa_p14_fr'
meshing:
  eval_rec: True
tracking:
  vis_freq: 50
  vis_inside_freq: 25
  ignore_edge_W: 100
  ignore_edge_H: 100
  seperate_LR: False
  const_speed_assumption: False
  lr: 0.001
  pixels: 200
  iters: 20 #10
mapping:
  every_frame: 10 #5
  vis_freq: 50
  vis_inside_freq: 30
  mesh_freq: 50
  ckpt_freq: 500
  keyframe_every: 50
  mapping_window_size: 5
  pixels: 1000
  iters_first: 1500
  iters: 60
camera_params:
  image_height: 768
  image_width: 1024
  fx: 1325.28279454
  fy: 1324.93728142
  cx: 979.237453101
  cy: 764.476037182
  png_depth_scale: 1000 #for depth image in png format
  crop_edge: 0