dataset_name: 'kitti'

meshing:
  eval_rec: True

tracking:
  vis_freq: 10
  vis_inside_freq: 5
  ignore_edge_W: 100
  ignore_edge_H: 100
  seperate_LR: False
  const_speed_assumption: True
  lr: 0.001
  pixels: 200
  iters: 10

mapping:
  every_frame: 1
  vis_freq: 10
  vis_inside_freq: 5
  mesh_freq: 10
  ckpt_freq: 500
  keyframe_every: 10
  mapping_window_size: 5
  pixels: 1000
  iters_first: 1500
  iters: 60

camera_params:
  image_height: 375
  image_width: 1242
  fx: 721.5377
  fy: 721.5377
  cx: 609.5593
  cy: 172.854
  png_depth_scale: 5000.0
  crop_edge: 0
